config/routes.rb
Rails.application.routes.draw do
  

  authenticated :user do
   root :to => 'bills#index', :as => :authenticated_root
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', :sessions => "sessions", :registrations => "registrations" }


  get '/following' => 'users#following'
  get '/followers' => 'users#followers'
  resources :users, only: [:edit, :show] do
    collection do
      patch :update_info
      get :remove_twitter
      get :remove_facebook
      post :send_mp_notification_fb
      post :send_mp_notification_tw
      post :send_mp_email
      post :accepted_terms
    end
    member do
      post :add_post_code_join_constituency
      post :add_user_to_party
    end
  end
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  match '/issues/:issue_name/' => 'issues#find_issues', via: [:get], :as => :issue_name
  resources :issues


  resources :parties


  resources :bills

  namespace :admin do
    resources :bills, only: [:index, :edit, :update, :destroy] do
      collection do
        get :voting_results
        post :get_voting_results
        post :mass_bill_import
      end
      member do
        post :add_issues
      end
    end
    resources :constituencies, only: [:index] do
      collection do
        post :populate_constituencies
      end
    end
    resources :issues, only: [:index, :create, :update, :destroy]
    resources :mps, only: [:index] do
      collection do
        post :populate_mps
        post :mass_mp_import
      end
    end
    resources :parties, only: [:index, :create, :update, :destroy]
    resources :users, only: [:index]
  end


  resources :settings, only: [:update]


  resources :relationships, only: [:create, :destroy]


  get '/my_votes' => 'votes#my_votes'
  resources :votes do
    member do
      patch :upvote
      patch :change_vote_comment
    end
  end


  resources :media_links


  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  get '/privacy' => 'static_pages#privacy'
  get '/terms' => 'static_pages#terms'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/jobs' => 'static_pages#jobs'
  get '/guidelines' => 'static_pages#guidelines'
  get '/feedback' => 'static_pages#feedback'


  post 'mailing_list_request' => 'static_pages#mailing_list_request'
  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	is_impressionable :counter_cache => true

	
	has_many :votes, dependent: :destroy

	has_many :bill_issues
	has_many :issues, through: :bill_issues

	has_many :media_links



	scope :with_matching_issue, ->(name = params[:issue_name]) {joins(:issues).merge(Issue.equal_to(name))}


	validates :simple_name, presence: true


	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    product = find_by_id(row["id"]) || new
	    product.attributes = row.to_hash.slice('progress', 'meaning', 'impact', 'cost', 'trending', 'simple_name', 'official_name', 'support', 'opposition')
	    product.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::Csv.new(file.path)
	  when ".xls" then Roo::Excel.new(file.path)
	  when ".xlsx" then Roo::Excelx.new(file.path)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |bill|
	      csv << bill.attributes.values_at(*column_names)
	    end
	  end
	end

	# learn to incorporate default options hash instead
	##def obliterate(things, options = {})
	##  default_options = {
	##    :gently => true, # obliterate with soft-delete
	##    :except => [], # skip obliterating these things
	##    :at => Time.now, # don't obliterate them until later
	##  }
	##  options.reverse_merge!(default_options)

	##  ...
	##end

	def self.get_index_bills(user, issue_name=nil)
		bills = find_bills_matching_issue(issue_name)

		if user
			bills = bills.select { |b| !b.votes.select { |v| v.voteable_id == user.id }.any? }
		end
		return bills
	end

	def self.find_bills_matching_issue(issue_name)
		if issue_name
			return Bill.with_matching_issue(issue_name).includes(:votes, :issues).order(:impressions_count)
		else
			return Bill.includes(:issues,:votes => :voteable).order(:impressions_count)
		end
	end

	def self.set_trending_bills(bills, trending_setting)
		if trending_setting
			return bills.first(3)
		else
			return bills.select { |b| b.trending }
		end
	end

	def self.set_common_bills(bills, trending_setting)
		if trending_setting
			return bills.offset(3)
		else
			return bills.select { |b| !b.trending }
		end
	end

	def top_comments(num=1, upvote=true)
		if votes.any?
			if upvote
				top_votes = votes.select { |b| b.in_favor && b.comment != "" }.to_a.sort_by{ |v| v.comment_score }.first(num)
			else
				top_votes = votes.select { |b| !b.in_favor && b.comment != "" }.to_a.sort_by{ |v| v.comment_score }.first(num)
			end
			return top_votes.to_a
		else
			return []
		end
	end

	def commented_votes
		return votes.where("comment != ?", "").to_a.sort_by{ |v| v.comment_score }
	end

	def get_user_vote(user)
		if user
			return votes.includes(:voteable).select { |v| v.voteable_id == user.id }.first
		else
			return false
		end
	end

	def get_mp_vote(mp)
		if mp
			return votes.to_a.select { |v| v.voteable_id == mp.id }.first
		else
			return false
		end
	end

end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::BaseController

	def index
		@bills = Bill.includes(:media_links, :issues).all.to_a
		@bill = Bill.new
		@issues = Issue.all
		@setting = Setting.first

		@bills = Kaminari.paginate_array(@bills).page(params[:page]).per(10)

		@s3_direct_post_primary = S3_BUCKET.presigned_post(key: "uploads/bill_photos/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
	end

	def create
		@bill = Bill.new(bill_params)
		
		if @bill.save
	    	redirect_to :back
		else
	  	render 'static_pages/home'
		end
	end

	def edit
		@bill = Bill.find(params[:id])
	end

	def update
		@bill = Bill.find(params[:id])

		if @bill.update_attributes(bill_params)
			respond_to do |format|
				format.html { redirect_to :back }
				format.js { render :partial => 'edit_bill_success.js.erb' }
			end
		else
			respond_to do |format|
				format.html { redirect_to :root_path }
				format.js { render :partial => 'edit_bill_fail.js.erb' }
			end
		end
		
	end

	def destroy
		@bill = Bill.find(params[:id])

		if @bill.destroy!
			redirect_to :back
		else
			redirect_to :root_path
		end
	end

	def add_issues
		@bill = Bill.find(params[:id])
		@bill.issues.clear
		@issues = params[:bill_issues]

		if @issues.any?
			@issues.each do |issue|
				@bill.bill_issues.create!(issue_id: issue)
			end
		end

		respond_to do |format|
	      format.html { redirect_to :back }
	      format.js
	 	end
	end

	def voting_results
		@bills = Bill.all
	end

	def get_voting_results
		@web_url = params[:web_url]
		@bill_id = params[:bill_id]
		Resque.enqueue(VotesSet, @bill_id, @web_url)
		redirect_to :back
	end

	def mass_bill_import
		Bill.import(params[:file])
		redirect_to :back
	end

	private

	  def bill_params
	  	params.require(:bill).permit(:progress, :meaning, :impact, :cost, :trending, :simple_name, :official_name, :support,
	  															 :opposition, :image_url, :social_image_url)
	  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	after_action :update_impressions_count, only: [:show]

	def index

		@failed = true if session[:failed_reg]
		session[:failed_reg] = nil

		@bills = Bill.get_index_bills(current_user)
		trending_setting = Setting.first.yes
		@trending = BillDecorator.decorate_collection(Bill.set_trending_bills(@bills, trending_setting))
		@common = BillDecorator.decorate_collection(Bill.set_common_bills(@bills, trending_setting))

		@commons = Kaminari.paginate_array(@common).page(params[:page]).per(20)

		respond_to do |format|
			format.html
			format.js
		  format.xls { send_data @bills.to_csv(col_sep: "\t") }
		end
		
	end

	def show
		@bill = Bill.includes(:media_links, :issues).find(params[:id]).decorate
		
		@vote = @bill.get_user_vote(current_user)
		@votes = @bill.commented_votes

		@votes_top_3_yes = @bill.top_comments(3)
		@votes_top_3_no = @bill.top_comments(3, false)

		respond_to do |format|
			format.html
			format.json { render :json => @bill }
		end

	end



	private

	  def update_impressions_count
	  	impressionist(@bill)
	  end
	  

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/admin/bills/_bill.html.erb
<% 
	ids = []
	bill.issues.each do |issue|
		ids << issue.id
	end 
%>
<li class="list-group-item">
	<div class="row">
		<div class="col-md-7">
			<%= bill.simple_name.upcase %>
			<div style="display:none;" id="bill_<%= bill.id %>_issues" class="issues_form">
				<%= form_tag add_issues_bill_path(bill.id) do %>
					<%= select_tag "bill_issues", options_from_collection_for_select(@issues, "id", "name", ids), multiple: true, class: "issue_select form-control" %>
					<%= submit_tag "Add Issues To Bills", :class => 'btn btn-default' %>
				<% end %>
			</div>



			<div style="display:none;" id="bill_<%= bill.id %>_media_links" class="issues_form">
				<h4>MEDIA LINKS</h4>
				<% media_links = bill.media_links %>
				<% if media_links.any? %>
					<% media_links.each do |media_link| %>
							<div class="row" style="padding-top: 10px;padding-bottom: 20px;border-bottom: 1px solid #C9C9C9;margin-bottom: 20px;">
								<div class="col-md-7">
									<%= media_link.web_url %>
								</div>
								<div class="col-md-5">
									<%= form_for media_link, method: :delete, html: {style: "display:inline;"}  do |f|%>
										<%# f.submit '<span class="glyphicon glyphicon-trash"></span> DELETE', style: "", :class=>'btn btn-sm btn-default' %>
										<%= button_tag(type: 'submit', class: "btn btn-xs btn-default") do %>
											<i class="glyphicon glyphicon-trash"></i> DELETE
										<% end %>
									<% end %>
								</div>
							</div>
					<% end %>
				<% end %>
				<div class="row">
					<div class="col-md-12">
						<%= form_for(bill.media_links.build(bill_id: bill.id)) do |f| %>
						  <div><%= f.hidden_field :bill_id %></div>
						  <%= f.text_field :web_url, placeholder: "MEDIA LINK", style: "height: 34px;position: relative;top: 2px;width: 288px;" %>
						  <%= f.submit "Add Media Link To Bill", :class => 'btn btn-default' %>
						<% end %>
					</div>
				</div>
			</div>





		</div>
		<div class="col-md-5"> 
			<a href="<%= edit_admin_bill_path(bill) %>" id="<%= bill.id %>" class="show_edit btn btn-xs btn-default"><span class="glyphicon glyphicon-pencil"></span> EDIT</a>
			<a href="" id="<%= bill.id %>" class="show_issues btn btn-xs btn-default"><span class="glyphicon glyphicon-plus-sign"></span> ISSUES</a>
			<a href="" id="<%= bill.id %>" class="show_media_links btn btn-xs btn-default"><span class="glyphicon glyphicon-plus-sign"></span> MEDIA LINKS</a>
			<%= form_for bill, method: :delete, html: {style: "display:inline;"}  do |f|%>
				<%# f.submit '<span class="glyphicon glyphicon-trash"></span> DELETE', style: "", :class=>'btn btn-sm btn-default' %>
				<%= button_tag(type: 'submit', class: "btn btn-xs btn-default") do %>
					<i class="glyphicon glyphicon-trash"></i> DELETE
				<% end %>
			<% end %>
		</div>
	</div>
</li>

app/views/admin/bills/_form.html.erb
<%= form_for bill do |f| %>
	<div class="form-group">
		<%= f.label :simple_name, "Common Name" %>
		<%= f.text_field :simple_name, class:'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :official_name, "Official Name" %>
		<%= f.text_field :official_name, class:'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :support, "Arguments For" %>
		<%= f.bootsy_area :support, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
	</div>
	<div class="form-group">
		<%= f.label :opposition, "Arguments Against" %>
		<%= f.bootsy_area :opposition, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
	</div>
	<div class="form-group">
		<%= f.label :meaning, "Meaning" %>
		<%= f.bootsy_area :meaning, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
	</div>
	<div class="form-group">
		<%= f.label :impact, "Who Does It Impact?" %>
		<%= f.bootsy_area :impact, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
	</div>
	<div class="form-group">
		<%= f.label :cost, "Potential Costs" %>
		<%= f.bootsy_area :cost, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
	</div>
	<div class="form-group">
		<%= f.label :trending, "Add To Top Trending?" %>
		<%= f.check_box :trending %>
	</div>
	<div class="form-group">
		<%= f.label :progress, "Current Bill Progress" %>
		<%= f.select :progress, options_for_select([ ["HOUSE OF COMMONS","house_of_commons"], ["HOUSE OF LORDS","house_of_lords"],["ROYAL ASSENT","royal_assent"] ], bill.progress),{}, {:class=>'form-control'} %>
	</div>
	<div class="form-group">
		<% if bill.image_url != "" %>
			<p>Current Bill Image</p>
			<img src="<%= bill.image_url %>">
		<% end %>
		<%= f.label :image_url %>
		<%= f.file_field :image_url %>
	</div>
	<div class="form-group">
		<% if bill.social_image_url != "" %>
			<p>Current Social Image</p>
			<img src="<%= bill.social_image_url %>">
		<% end %>
		<%= f.label :social_image_url %>
		<%= f.file_field :social_image_url %>
	</div>
	<%= f.submit "Save Bill Edits", :class => 'btn btn-lg btn-default', id: "edit_bill_btn" %>
<% end %>

app/views/admin/bills/edit.html.erb
<%= render partial: "form", locals: {bill: @bill} %>

app/views/admin/bills/index.html.erb
<%= content_tag "div", id: "json_data_admins_bills", data: {s3_fields: @s3_direct_post_primary.fields, s3_url: @s3_direct_post_primary.url } do %>
<% end %>

<div class="container">
<div class="row admin-content">
	<div class="col-sm-9" role="main">
		<div class="row">
			<div class="col-md-12">
				<h2 class="text-din text-uppercase" style="margin-top: 0;">BILLS</h2>
				<%= form_for @setting do |f| %>
					<%= f.label :yes, "Automatic Trending?" %>
					<%= f.check_box :yes %>
					<%# f.submit "Save Trending Setting", class:'btn btn-default' %>
					<%= button_tag(type: 'submit', class: "btn btn-sm btn-default") do %>
						<i class="fa fa-floppy-o"></i> Save Trending Setting
					<% end %>
				<% end %>

				<h2 class="text-din text-uppercase">
				  Download Bills
				</h2>
				<div class="form-group">
					 <%# link_to "Excel", bills_path(format: "xls") %>
					 <%= link_to(bills_path(format: "xls"), class: 'btn btn-sm btn-default') do %>
					 	<i class="fa fa-file-excel-o"></i> Excel
					 <% end %>
				</div>

				<h2 class="text-din text-uppercase">Mass Import Bills</h2>
				<%= form_tag mass_bill_import_admin_bills_path, multipart: true do %>
					<div class="form-group">
						<%= file_field_tag :file %>
					</div>
					<%# submit_tag "Import Bills", class:'btn btn-default' %>
					<div class="form-group">
						<%= button_tag(type: 'submit', class: "btn btn-sm btn-default") do %>
							<i class="glyphicon glyphicon-import"></i> Import Bills
						<% end %>
					</div>
				<% end %>
			</div>
			<div class="col-md-12">
				<h2 class="text-din text-uppercase">Manage Bills</h2>
			</div>
			<div class="col-md-12">
				 
				<div class="row">
				 	<div class="col-md-12" style="padding-top: 15px;">
				 		<% if @bills.any? %>
							<%= paginate @bills %>
						<% end %>
				 	</div>
				</div>


				<% if @bills.any? %>
				<ul class="list-group">
					<%= render partial: "bill", collection: @bills, as: :bill %>				
				</ul>
				<% end %>
			</div>
			<div class="col-md-12">
				<h2 class="text-din text-uppercase">Add Bill</h2>
			</div>
			<div class="col-md-12">
				<a href="javascript:;" class="show_add btn btn-xs btn-default"><span class="glyphicon glyphicon-plus"></span> ADD</a>
				<div style="display:none;" class="add_form">
				<%= form_for @bill do |f| %>
				    <div class="form-group">
						<%= f.label :simple_name, "Common Name" %>
						<%= f.text_field :simple_name, required: true, class:'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :official_name, "Official Name" %>
						<%= f.text_field :official_name, required: true, class:'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :support, "Arguments For" %>
						<%= f.bootsy_area :support, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
					</div>
					<div class="form-group">
						<%= f.label :opposition, "Arguments Against" %>
						<%= f.bootsy_area :opposition, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
					</div>
					<div class="form-group">
						<%= f.label :meaning, "Meaning" %>
						<%= f.bootsy_area :meaning, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
					</div>
					<div class="form-group">
						<%= f.label :impact, "Who Does It Impact?" %>
						<%= f.bootsy_area :impact, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
						<%= f.label :cost, "Potential Costs" %>
					</div>
					<div class="form-group">
						<%= f.bootsy_area :cost, editor_options: { color: false,image: false, font_styles: false }, style:'width:100%;height:150px;' %>
					</div>
					<div class="form-group">
						<%= f.label :trending, "Add To Top Trending?" %>
						<%= f.check_box :trending %>
					</div>
					<div class="form-group">
						<%= f.label :progress, "Current Bill Progress" %>
						<%= f.select :progress, options_for_select([ ["HOUSE OF COMMONS","house_of_commons"], ["HOUSE OF LORDS","house_of_lords"],["ROYAL ASSENT","royal_assent"] ]),{}, {:class=>'form-control'} %>
					</div>
					<div class="form-group">
						<%= f.label :image_url %>
						<%= f.file_field :image_url %>
					</div>
					<div class="form-group">
						<%= f.label :social_image_url %>
						<%= f.file_field :social_image_url %>
					</div>
					<div class="form-group">
						<%# f.submit "Add New Bill", :class => 'btn btn-lg btn-primary' %>
						<%= button_tag(type: 'submit', class: "btn btn-lg btn-default") do %>
							<i class="glyphicon glyphicon-plus"></i> Add New Bill
						<% end %>
					</div>
				<% end %>
				</div>
			</div>
		</div>
	</div>
	<%= render "admin/sidebar" %>
</div>
</div><!-- .container -->

<div class="modal fade modal-alert modal-danger" id="warningModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1><i class="fa fa-exclamation-triangle"></i></h1>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete this bill? This cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<input type="hidden" id="warning-rel" value="" />
				<a href="javascript:;" id="do-warning" class="btn btn-flat btn-danger"><i class="fa fa-check"></i> Yes</a>
				<a href="javascript:;" class="btn btn-flat btn-outline" data-dismiss="modal"><i class="fa fa-times"></i> No</a>
			</div>
		</div>
	</div>
</div>

app/views/admin/bills/voting_results.html.erb
<div class="container">
	<div class="row admin-content">
		<div class="col-sm-9" role="main">
			<%= form_tag get_voting_results_admin_bills_path do %>
				<div class="form-group">
					<%# select_tag :bill_id, options_from_collection_for_select(@bills, 'id', 'simple_name') %>
					<%= select_tag "bill_id", options_from_collection_for_select(@bills, "id", "simple_name"), multiple: false, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= text_field_tag :web_url, '', class:'form-control' %>
					<%# f.text_field :simple_name, class:'form-control' %>
				</div>
				<div class="form-group">
				<%# submit_tag "Get Results" %>
				<%= button_tag(type: 'submit', class: "btn btn-default") do %>
					<i class="fa fa-arrow-circle-o-down"></i> Get Results
				<% end %>
				</div>
			<% end %>
		</div>
		<%= render "admin/sidebar" %>
	</div><!-- .admin-content-->
</div><!-- .container -->