config/routes.rb
Rails.application.routes.draw do
  

  authenticated :user do
   root :to => 'bills#index', :as => :authenticated_root
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', :sessions => "sessions", :registrations => "registrations" }


  get '/following' => 'users#following'
  get '/followers' => 'users#followers'
  resources :users, only: [:edit, :show] do
    collection do
      patch :update_info
      get :remove_twitter
      get :remove_facebook
      post :send_mp_notification_fb
      post :send_mp_notification_tw
      post :send_mp_email
      post :accepted_terms
    end
    member do
      post :add_post_code_join_constituency
      post :add_user_to_party
    end
  end
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  match '/issues/:issue_name/' => 'issues#find_issues', via: [:get], :as => :issue_name
  resources :issues


  resources :parties


  resources :bills

  namespace :admin do
    resources :bills, only: [:index, :edit, :update, :destroy] do
      collection do
        get :voting_results
        post :get_voting_results
        post :mass_bill_import
      end
      member do
        post :add_issues
      end
    end
    resources :constituencies, only: [:index] do
      collection do
        post :populate_constituencies
      end
    end
    resources :issues, only: [:index, :create, :update, :destroy]
    resources :mps, only: [:index] do
      collection do
        post :populate_mps
        post :mass_mp_import
      end
    end
    resources :parties, only: [:index, :create, :update, :destroy]
    resources :users, only: [:index]
  end


  resources :settings, only: [:update]


  resources :relationships, only: [:create, :destroy]


  get '/my_votes' => 'votes#my_votes'
  resources :votes do
    member do
      patch :upvote
      patch :change_vote_comment
    end
  end


  resources :media_links


  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  get '/privacy' => 'static_pages#privacy'
  get '/terms' => 'static_pages#terms'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/jobs' => 'static_pages#jobs'
  get '/guidelines' => 'static_pages#guidelines'
  get '/feedback' => 'static_pages#feedback'


  post 'mailing_list_request' => 'static_pages#mailing_list_request'
  root 'bills#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  has_many :identities, dependent: :destroy

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower


  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy

  has_many :votes, as: :voteable
  has_many :comments

  belongs_to :party
  belongs_to :constituency

  has_many :comment_votes


  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :async

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          picture_url: auth.info.image,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      #fix this identity.user = user
    end
    identity.user_id = user.id
    identity.save!
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end

  def vote!(other_user)
    votes.create!(followed_id: other_user.id)
  end

  def upvote!(comment)
    comment_votes.create!(vote_id: comment.id)
  end

  def upvoted?(comment)
    comment_votes.find_by(vote_id: comment.id)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

	def index
		@users = User.all
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy, :finish_signup, :edit]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_idents, only: [:edit]
  before_action :profile_action, only: [:show]
  skip_filter :check_email_format
  before_filter :authenticate_user!

  # GET /users/:id.:format
  def show
    # authorize! :read, @user
    @votes = @user.votes.includes(:bill, :voteable)
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
    @parties = Party.all.to_a
    @constituency = @user.constituency
    @s3_direct_user_image = S3_BUCKET.presigned_post(key: "uploads/user_photos/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)

    respond_to do |format|
      format.html
      format.json { render :json => @user }
    end
  end

  # PATCH/PUT /users/:id.:format
  def update_info
    # authorize! :update, @user
    @user = User.find(current_user.id)
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, bypass: true)
        format.html { redirect_to root_path, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    unless @user.email.include? "change@me"
      redirect_to edit_user_path(@user.id)
    else
    # authorize! :update, @user 
      if request.patch? && params[:user] && params[:user][:email]
        if @user.update_attributes(user_params)
          sign_in(@user, bypass: true)
          redirect_to edit_user_path(@user.id), notice: 'Your profile was successfully updated.'
        else
          flash[:notice] = "Email blank or already taken!  If you already have an account, try logging in with either Facebook or Email."
          @show_errors = true
        end
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def remove_twitter
    current_user.identities.find_by(provider: "twitter").destroy!

    redirect_to root_path
  end

  def remove_facebook
    current_user.identities.find_by(provider: "facebook").destroy!

    redirect_to root_path
  end

  def add_post_code_join_constituency
    require 'open-uri'
    encoded_url_3 = URI.encode("http://www.doogal.co.uk/ShowMap.php?postcode=#{params[:postcode]}")
    @doc_3 = Nokogiri::HTML(open(encoded_url_3))
    @node = @doc_3.xpath('//td[text()="Constituency: "]').first
    constituency_name_web = @node.next_element.text
    @constituency = Constituency.find_by(name: constituency_name_web)
    @user = User.find(params[:id])
    @user.post_code = params[:postcode]
    @user.constituency_id = @constituency.id
    if @user.save
      respond_to do |format|
        format.html {redirect_to :back}
        format.js {render :partial => 'show_user_mp.js.erb'}
      end
    else
      redirect_to edit_user_path(current_user.id)
    end
  end

  def add_user_to_party
    @party = Party.find_by(name: params[:party_name])
    @parties = Party.all
    @user = User.find(params[:id])
      @user.party_id = @party.id
    if @user.save
      respond_to do |format|
        format.html {redirect_to :back}
        format.js {render :partial => 'add_user_to_party.js.erb'}
      end
    end
  end

  def followers
    @users = current_user.followers
  end

  def following
    @users = current_user.followed_users
  end

  def send_mp_notification_fb
    Resque.enqueue(NotifyMpFb, params[:content], current_user.id)
    respond_to do |format|
      format.js {render :partial => 'close_notify_modal_fb.js.erb'}
    end
  end

  def send_mp_notification_tw
    Resque.enqueue(NotifyMpTw, params[:content], current_user.id)
    respond_to do |format|
      format.js {render :partial => 'close_notify_modal_tw.js.erb'}
    end
  end

  def send_mp_email
    Resque.enqueue(NotifyMpEmail, params[:content], current_user.id)
    respond_to do |format|
      format.js {render :partial => 'close_notify_modal_email.js.erb'}
    end
  end

  def accepted_terms
    user = current_user
      user.accepted_terms = true
    user.save

    respond_to do |format|
      format.js {render :partial => 'close_notify_modal_terms.js.erb'}
    end
  end

  
  private
    def set_user
      if User.where(id: params[:id]).any?
        @user = User.find(params[:id])
      else
        redirect_to root_path
      end
    end

    def user_params
      accessible = [ :name, :email, :allow_profile_view, :bio, :fb_link, :tw_link, :insta_link, :youtube_link, :web_link, :street_addr, :city, :phone, :picture_url ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end

    def profile_action
      @user = User.find(params[:id])
      if @user.allow_profile_view
        redirect_to bills_path
      end
    end

    def correct_user
      unless @user == current_user
        redirect_to root_path
      end
    end

    def set_idents
      @idents = []

      if user_signed_in?
        current_user.identities.each do |i|
          @idents << i.provider
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_user_to_party.js.erb
$("#party_list").html("<%= escape_javascript(render partial: 'users/party_list_partial', :locals => { :parties => @parties }) %>");
<% if @user.party_id %>
    $('.add_user_to_party_link#' + <%= @user.party_id %>).css({color: '#ef4747', border: '1px solid #333', padding: '10px 14px 7px'});
<% end %>

app/views/users/_aws_upload.html.erb
<script type="text/javascript">
$(function() {
  $('.user_image_form').find("input:file").each(function(i, elem) {
    var fileInput    = $(elem);
    var form         = $(fileInput.parents('form:first'));
    var submitButton = form.find('input[type="submit"]');
    fileInput.fileupload({
      fileInput:       fileInput,
      url:             '<%= @s3_direct_user_image.url %>',
      type:            'POST',
      autoUpload:       true,
      formData:         <%= @s3_direct_user_image.fields.to_json.html_safe %>,
      paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
      dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
      replaceFileInput: false,
      progressall: function (e, data) {
       
      },
      start: function (e) {
        submitButton.prop('disabled', true);
        $(submitButton).val('Saving...');
        console.log('this is working');
        
      },
      done: function(e, data) {
        submitButton.prop('disabled', false);

        // extract key and generate URL from response
        var key   = $(data.jqXHR.responseXML).find("Key").text();
        var url   = '//<%= @s3_direct_user_image.url.host %>/' + key;

        // create hidden field
        var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url })
        form.append(input);
        console.log(data);
        $('.user_image_form').trigger("submit.rails");
      },
      fail: function(e, data) {
        submitButton.prop('disabled', false);

       
      }
    });
  });
});
</script>

app/views/users/_close_notify_modal_email.js.erb
$('#mpEmailModal').modal('hide');
ga('send', 'event', 'MPs', 'Message', 'Email');

app/views/users/_close_notify_modal_fb.js.erb
$('#noFBModal').modal('hide');
ga('send', 'event', 'MPs', 'Message', 'No FB');

app/views/users/_follow.html.erb
<div class="row" style="margin-bottom: 20px; border: 1px solid rgb(192, 192, 192);border-left: none;">
	<div class="col-sm-2 bg-grey  text-uppercase" style="padding: 0px; border-right: 1px solid #c0c0c0;border-left:1px solid #c0c0c0;">
		<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
		  <div><%= f.hidden_field :followed_id %></div>
		  <%= f.submit "Follow #{@user.name}", class: "text-din-medium", style: "background: transparent none repeat scroll 0% 0%;width: 100%;height: 40px; border: none;" %>
		<% end %>
	</div>
	<div class="col-sm-10 text-din text-uppercase" style="padding: 10px;">
	</div>
</div>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_followers_list.html.erb
<div class="list-group-item">
	<p style="margin: 0;"><a href="<%= user_path(user.id) %>" style="font-size: 18px;"><%= user.name %></a></p>
</div>

app/views/users/_mp_side_partial.html.erb
<div class="col-md-6">
  <div class="row">

    <div class="col-sm-4">
      <img src="<%= @mp.picture_url if @mp && @mp.picture_url %>" style="height:141px;width:141px;background-color:#10b8b8;border-radius:50%;">

    </div>
    <div class="col-sm-8">
      <div id="mp-info" style="display:inline-block;">
        <div style="text-transform:uppercase;" class="clearfix">
          <%= @mp.name %>
        </div>
        <%= render :partial => 'mps/side_partial', :locals => { :mp => @mp } %>
        <div style="text-transform:uppercase;padding-bottom:4px;" class="clearfix">
          <%= @mp.phone %>
        </div>
      </div><!-- #mp-info -->
    </div>
  </div>
</div>

app/views/users/_mp_side_partial_fade.html.erb
<div class="col-md-6" id="hidden_mp" style="display:none;">
  <div class="row">

    <div class="col-sm-4">
      <img src="<%= @mp.picture_url if @mp && @mp.picture_url %>" style="height:141px;width:141px;background-color:#10b8b8;border-radius:50%;">

    </div>
    <div class="col-sm-8">
      <div id="mp-info" style="display:inline-block;">
        <div style="text-transform:uppercase;padding-bottom:4px;" class="clearfix">
          <%= @mp.name %>
        </div>
        <%= render :partial => 'mps/side_partial', :locals => { :mp => @mp } %>
        <div style="text-transform:uppercase;padding-bottom:4px;" class="clearfix">
          <%= @mp.phone %>
        </div>
      </div><!-- #mp-info -->
    </div>
  </div>
</div>

app/views/users/_party_list_partial.html.erb
<div class="row" style="padding-bottom: 20px;border-bottom: 1px solid #c0c0c0;margin-bottom: 20px;">
  <div class="col-md-12 text-center">
    <h4 class="text-din text-center" style="padding-bottom: 40px;">PICK YOUR PARTY</h4>
    <% 
      if parties.any? 
      parties.each do |party|
    %>
      <p style="display:inline;padding: 15px;line-height: 2.5em;"><a href="javascript:;" class="add_user_to_party_link text-din text-uppercase" id="<%= party.id %>"><%= party.name %></a></p>
    <% end %>
    <% end %>
    <div style="clear:both;"></div>
    <div style="display:none;">
      <%= form_tag add_user_to_party_user_path(@user), id: "add_party", remote: true do %>
        <%= hidden_field_tag :party_name, "" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_show_user_mp.js.erb
$("#mp_side").html("<%= escape_javascript(render partial: "users/mp_side_partial_fade") %>");
$('#hidden_mp').fadeIn(4000);
$('#meet_div').fadeIn(4000);

app/views/users/edit.html.erb
<%= content_tag "div", id: "json_data_users_edit", data: {mp: @mp, s3_fields: @s3_direct_user_image.fields, s3_url: @s3_direct_user_image.url} do %>
<% end %>



  
<h2 class="text-din text-center" style="padding-bottom: 40px;">MEET</h2>
 


<div class="row" style="padding-bottom: 40px;border-bottom: 1px solid #c0c0c0;margin-bottom: 20px;">


  <div class="col-md-6">
    <div class="row">

      <div class="col-sm-4">
        <div style="height:141px;width:141px;background-color:transparent;">
          <% if @user.picture_url %>
            <img src="<%= @user.picture_url %>" style="height:141px;width:141px;background-color:transparent;border-radius:50%;">
          <% end %>
          <%= form_for @user, url: update_info_users_path, html: {class: "user_image_form"} do |f| %>
            <%= f.file_field :picture_url, style: "position: absolute;bottom: 0px;opacity: 0;z-index: 99999;cursor: pointer;width: 141px;" %>
            <%= f.submit "Change Image", style: "", class: "change_image_btn" %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-8" class="text-din">
        <h3 class="text-uppercase" style="font-family: dinRegular;font-size: 14px;">HI <%= @user.name %></h3>
        <p style="font-family: dinRegular;font-size: 12px;color: #999;">Please enter your postcode.  We need this to find your local MP.</p>

        <%= form_tag add_post_code_join_constituency_user_path(current_user), id: "add_postcode", remote: true do %>
          <div class="form-group" style="">
             <%= text_field_tag :postcode, @user.post_code, class: 'form-control text-center', style: "width: 30%;display: inline;min-width: 90px;" %>
           </div>
            <%# submit_tag 'submit', id: "postcode_check" %>
            <div class="form-group" style="">
               <%= button_tag(type: 'submit', id: "postcode_check", class: "btn btn-default text-center", style: "border-radius: 0px;width: 30%;display: inline;min-width: 90px;") do %>
                 SUBMIT <i class="fa fa-caret-right"></i>
               <% end %>
             </div>

        <% end %>

      </div>
    </div>
  </div>




  <div id="mp_side">
    <% if @mp %>
      <%= render "users/mp_side_partial" %>
    <% end %>
  </div>




</div>




<div id="party_list">
  <%= render partial: "users/party_list_partial", :locals => { :parties => @parties } %>
</div>





<div style="padding-bottom:20px; border-bottom: 1px solid #c0c0c0;">
  <%= form_for(@user, :url => { :action => "update_info" } ) do |f| %>


    <h4 class="text-din">ABOUT YOU</h4>
    <div class="field form-group">
      <%= f.text_area :bio, :class => 'form-control text-din', placeholder: "ENTER YOUR BIO"  %>
    </div>


    <h4 class="text-din">SOCIAL MEDIA LINKS</h4>
    <div class="row">
    	<div class="col-sm-6">
  			<div class="field form-group">
  			  <%= f.text_field :fb_link, :class => 'form-control text-din', placeholder: "FACEBOOK"  %>
  			</div>
  		</div>
  		<div class="col-sm-6">
  			<div class="field form-group">
  			  <%= f.text_field :tw_link, :class => 'form-control text-din', placeholder: "TWITTER"  %>
  			</div>
  		</div>
  	</div>
    <div class="row">
    	<div class="col-sm-6">
  			<div class="field form-group">
  			  <%= f.text_field :insta_link, :class => 'form-control text-din', placeholder: "INSTAGRAM"  %>
  			</div>
  		</div>
  		<div class="col-sm-6">
  			<div class="field form-group">
  			  <%= f.text_field :youtube_link, :class => 'form-control text-din', placeholder: "YOUTUBE"  %>
  			</div>
  		</div>
  	</div>
    <div class="field form-group">
      <%= f.text_field :web_link, :class => 'form-control text-din', placeholder: "WEBSITE"  %>
    </div>


    <h4 class="text-din">ADDRESS</h4>
    <div class="field form-group">
      <%= f.text_field :street_addr, :class => 'form-control text-din', placeholder: "STREET"  %>
    </div>
    <div class="row">
    	<div class="col-sm-6">
  			<div class="field form-group">
  			  <%= f.text_field :city, :class => 'form-control text-din', placeholder: "CITY"  %>
  			</div>
  		</div>
  		<div class="col-sm-6">
  			<div class="field form-group">
  			  <%= f.text_field :post_code, :class => 'form-control text-din', placeholder: "POSTCODE", disabled: true  %>
  			</div>
  		</div>
  	</div>
    <div class="field form-group">
      <%= f.text_field :phone, :class => 'form-control text-din', placeholder: "PHONE (OPTIONAL)"  %>
    </div>


    <h4 class="text-din">PUBLIC PROFILE</h4>
    <%= f.label :allow_profile_view, "MAKE YOUR PROFILE PRIVATE?", style: "font-family: dinRegular;font-size: 12px;font-weight: normal;" %>
    <%= f.check_box :allow_profile_view %>
    <p style="font-family: dinRegular;font-size: 12px;font-weight: normal;">LINK TO YOUR PROFILE: www.whip.org.uk/users/<%= current_user.id %></p>


    <div class="action_container clearfix">
    	<div class="pull-right">
  			<%= button_tag(type: 'submit', class: "btn btn-default btn-square", style: "font-size: 12px;") do %>
             		SAVE DETAILS
       	<% end %>
     	</div>
    </div>


  <% end %>
</div>



<div style="padding-top:20px;text-align: right;padding-bottom: 60px;">
  <%= button_to 'CANCEL MY ACCOUNT'.html_safe, registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-default btn-square', style: 'font-size: 12px;' %>
</div>

app/views/users/followers.html.erb
<div class="container max_924 padding_bottom_60">

	<%= render :partial => 'shared/top_banner_with_names', :locals => { :user => current_user } %>

	<h4 class="text-din padding_bottom_24">Users Following You</h4>

	<% if @users.any? %>
		<%= render partial: "users/followers_list", collection: @users, as: :user %>
	<% end %>

</div>

app/views/users/show.html.erb
<div class="container max_924">


	<%= render :partial => 'shared/top_banner_with_names', :locals => { :user => current_user } %>
	<%= render 'follow_form' if signed_in? %>

	<div class="row trending_bills">
		<% if @votes.any? %>
		 	<%= render partial: "users/vote_list", collection: @votes, as: :vote %>
		<% end %>
	</div>


</div><!-- .container max 924 -->