config/routes.rb
Rails.application.routes.draw do
  

  authenticated :user do
   root :to => 'bills#index', :as => :authenticated_root
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', :sessions => "sessions", :registrations => "registrations" }


  get '/following' => 'users#following'
  get '/followers' => 'users#followers'
  resources :users, only: [:edit, :show] do
    collection do
      patch :update_info
      get :remove_twitter
      get :remove_facebook
      post :send_mp_notification_fb
      post :send_mp_notification_tw
      post :send_mp_email
      post :accepted_terms
    end
    member do
      post :add_post_code_join_constituency
      post :add_user_to_party
    end
  end
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  match '/issues/:issue_name/' => 'issues#find_issues', via: [:get], :as => :issue_name
  resources :issues


  resources :parties


  resources :bills

  namespace :admin do
    resources :bills, only: [:index, :edit, :update, :destroy] do
      collection do
        get :voting_results
        post :get_voting_results
        post :mass_bill_import
      end
      member do
        post :add_issues
      end
    end
    resources :constituencies, only: [:index] do
      collection do
        post :populate_constituencies
      end
    end
    resources :issues, only: [:index, :create, :update, :destroy]
    resources :mps, only: [:index] do
      collection do
        post :populate_mps
        post :mass_mp_import
      end
    end
    resources :parties, only: [:index, :create, :update, :destroy]
    resources :users, only: [:index]
  end


  resources :settings, only: [:update]


  resources :relationships, only: [:create, :destroy]


  get '/my_votes' => 'votes#my_votes'
  resources :votes do
    member do
      patch :upvote
      patch :change_vote_comment
    end
  end


  resources :media_links


  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  get '/privacy' => 'static_pages#privacy'
  get '/terms' => 'static_pages#terms'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/jobs' => 'static_pages#jobs'
  get '/guidelines' => 'static_pages#guidelines'
  get '/feedback' => 'static_pages#feedback'


  post 'mailing_list_request' => 'static_pages#mailing_list_request'
  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	is_impressionable :counter_cache => true

	
	has_many :votes, dependent: :destroy

	has_many :bill_issues
	has_many :issues, through: :bill_issues

	has_many :media_links



	scope :with_matching_issue, ->(name = params[:issue_name]) {joins(:issues).merge(Issue.equal_to(name))}


	validates :simple_name, presence: true


	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    product = find_by_id(row["id"]) || new
	    product.attributes = row.to_hash.slice('progress', 'meaning', 'impact', 'cost', 'trending', 'simple_name', 'official_name', 'support', 'opposition')
	    product.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::Csv.new(file.path)
	  when ".xls" then Roo::Excel.new(file.path)
	  when ".xlsx" then Roo::Excelx.new(file.path)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |bill|
	      csv << bill.attributes.values_at(*column_names)
	    end
	  end
	end

	# learn to incorporate default options hash instead
	##def obliterate(things, options = {})
	##  default_options = {
	##    :gently => true, # obliterate with soft-delete
	##    :except => [], # skip obliterating these things
	##    :at => Time.now, # don't obliterate them until later
	##  }
	##  options.reverse_merge!(default_options)

	##  ...
	##end

	def self.get_index_bills(user, issue_name=nil)
		bills = find_bills_matching_issue(issue_name)

		if user
			bills = bills.select { |b| !b.votes.select { |v| v.voteable_id == user.id }.any? }
		end
		return bills
	end

	def self.find_bills_matching_issue(issue_name)
		if issue_name
			return Bill.with_matching_issue(issue_name).includes(:votes, :issues).order(:impressions_count)
		else
			return Bill.includes(:issues,:votes => :voteable).order(:impressions_count)
		end
	end

	def self.set_trending_bills(bills, trending_setting)
		if trending_setting
			return bills.first(3)
		else
			return bills.select { |b| b.trending }
		end
	end

	def self.set_common_bills(bills, trending_setting)
		if trending_setting
			return bills.offset(3)
		else
			return bills.select { |b| !b.trending }
		end
	end

	def top_comments(num=1, upvote=true)
		if votes.any?
			if upvote
				top_votes = votes.select { |b| b.in_favor && b.comment != "" }.to_a.sort_by{ |v| v.comment_score }.first(num)
			else
				top_votes = votes.select { |b| !b.in_favor && b.comment != "" }.to_a.sort_by{ |v| v.comment_score }.first(num)
			end
			return top_votes.to_a
		else
			return []
		end
	end

	def commented_votes
		return votes.where("comment != ?", "").to_a.sort_by{ |v| v.comment_score }
	end

	def get_user_vote(user)
		if user
			return votes.includes(:voteable).select { |v| v.voteable_id == user.id }.first
		else
			return false
		end
	end

	def get_mp_vote(mp)
		if mp
			return votes.to_a.select { |v| v.voteable_id == mp.id }.first
		else
			return false
		end
	end

end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::BaseController

	def index
		@bills = Bill.includes(:media_links, :issues).all.to_a
		@bill = Bill.new
		@issues = Issue.all
		@setting = Setting.first

		@bills = Kaminari.paginate_array(@bills).page(params[:page]).per(10)

		@s3_direct_post_primary = S3_BUCKET.presigned_post(key: "uploads/bill_photos/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
	end

	def create
		@bill = Bill.new(bill_params)
		
		if @bill.save
	    	redirect_to :back
		else
	  	render 'static_pages/home'
		end
	end

	def edit
		@bill = Bill.find(params[:id])
	end

	def update
		@bill = Bill.find(params[:id])

		if @bill.update_attributes(bill_params)
			respond_to do |format|
				format.html { redirect_to :back }
				format.js { render :partial => 'edit_bill_success.js.erb' }
			end
		else
			respond_to do |format|
				format.html { redirect_to :root_path }
				format.js { render :partial => 'edit_bill_fail.js.erb' }
			end
		end
		
	end

	def destroy
		@bill = Bill.find(params[:id])

		if @bill.destroy!
			redirect_to :back
		else
			redirect_to :root_path
		end
	end

	def add_issues
		@bill = Bill.find(params[:id])
		@bill.issues.clear
		@issues = params[:bill_issues]

		if @issues.any?
			@issues.each do |issue|
				@bill.bill_issues.create!(issue_id: issue)
			end
		end

		respond_to do |format|
	      format.html { redirect_to :back }
	      format.js
	 	end
	end

	def voting_results
		@bills = Bill.all
	end

	def get_voting_results
		@web_url = params[:web_url]
		@bill_id = params[:bill_id]
		Resque.enqueue(VotesSet, @bill_id, @web_url)
		redirect_to :back
	end

	def mass_bill_import
		Bill.import(params[:file])
		redirect_to :back
	end

	private

	  def bill_params
	  	params.require(:bill).permit(:progress, :meaning, :impact, :cost, :trending, :simple_name, :official_name, :support,
	  															 :opposition, :image_url, :social_image_url)
	  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	after_action :update_impressions_count, only: [:show]

	def index

		@failed = true if session[:failed_reg]
		session[:failed_reg] = nil

		@bills = Bill.get_index_bills(current_user)
		trending_setting = Setting.first.yes
		@trending = BillDecorator.decorate_collection(Bill.set_trending_bills(@bills, trending_setting))
		@common = BillDecorator.decorate_collection(Bill.set_common_bills(@bills, trending_setting))

		@commons = Kaminari.paginate_array(@common).page(params[:page]).per(20)

		respond_to do |format|
			format.html
			format.js
		  format.xls { send_data @bills.to_csv(col_sep: "\t") }
		end
		
	end

	def show
		@bill = Bill.includes(:media_links, :issues).find(params[:id]).decorate
		
		@vote = @bill.get_user_vote(current_user)
		@votes = @bill.commented_votes

		@votes_top_3_yes = @bill.top_comments(3)
		@votes_top_3_no = @bill.top_comments(3, false)

		respond_to do |format|
			format.html
			format.json { render :json => @bill }
		end

	end



	private

	  def update_impressions_count
	  	impressionist(@bill)
	  end
	  

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill.html.erb
<div class="text-center masonary_sizing">
	<a href='<%= bill_path(bill) %>' class='bricks'>

		<div class="panel panel-bills small-bill-highlight panel-body">
			<div class="common-bill" style="background-image: url('<%= bill.set_background_img %>'); border-radius: 12px;">
				<p class="common-bill-title" style="font-size: 18px;padding-top: 22px;"><%= bill.simple_name %></p>
				<p class="common-bill-title"><small><%= "#{bill.official_name_text(bill)}" %></small></p>
			</div>


			<div class="text-center text-din" style="padding-bottom:22px;border-bottom: 1px solid #a1a1a1; ">
				<h2 class="header-argument-for">ARGUMENTS FOR</h2>
				<%= bill.support.html_safe %>
			</div>
			<div class="text-center text-din" style="padding-bottom:22px;border-bottom: 1px solid #a1a1a1; ">
				<h2 class="header-argument-against" style="margin-top:20px;">ARGUMENTS AGAINST</h2>
				<%= bill.opposition.html_safe %>
			</div>



			<div class="row" style="margin: 0 5px 10px 5px;padding: 0 5px;">
				<div class="col-sm-6 vote-button-yes">
					<%= bill.set_yes_vote_btn(current_user) %>
				</div>
				<div class="col-sm-6 vote-button-no">
					<%= bill.set_no_vote_btn(current_user) %>
				</div>
			</div>
		</div><!--.panel-->


	</a>
</div><!-- .col-sm-6 -->
		

app/views/bills/_bill_comments.html.erb
<div style="padding:0px 0px 15px;">

	<% if user_vote %>
		<h2 class="text-din" style="margin-bottom:0px;">THANKS FOR VOTING</h2>
		<p style="font-family: dinRegular; margin-bottom:24px;">If desired, update your previous thoughts in the space below!</p>

		<%= form_for user_vote, url: vote_path(user_vote) do |f| %>
			<%= f.text_area :comment, style: "    width: 400px;height: 120px; resize: none; border: 1px solid #ddd; font-size: 14px; font-family: dinRegular;padding: 8px;" %><br>
			<%= f.submit "EDIT COMMENT", class: "edit_comment_btn" %>
		<% end %>

	<% else %>
		<h2 class="text-din" style="">JOIN THE DISCUSSION</h2>
		<p style="font-family: dinRegular;">Cast your vote above to have your thoughts broadcast to the community!</p>
	
	<% end %>
</div>

<h2 class="text-din" style="">BILL COMMENTS</h2>
<%= render partial: "votes/comment", collection: votes, as: :vote %>

app/views/bills/_top_banner_with_names.html.erb
<%
	_svg = false
%>
<% if user_signed_in? %>
	<div class="row" style="padding-bottom: 20px;">
		<div class="col-sm-4" style="padding-left:0;">
			<div class="row">
				<div class="col-sm-12">
					<% if current_user.picture_url %>
						<div id="user-image" style="text-transform:uppercase;display:inline-block;vertical-align:top;padding-right:12px;">
							<img src="<%= current_user.picture_url %>" style="height:65px;width:65px;background-color:#10b8b8;border:none;border-radius:50%;" />
						</div>
					<% else %>
						<div id="user-image" style="text-transform:uppercase;display:inline-block;vertical-align:top;padding-right:12px;">
							<img src="<%= image_path('blank.png') %>" style="height:65px;width:65px;background-color:#10b8b8;border:none;border-radius:50%;" />
						</div>
					<% end %>
					<div id="user-info" style="display:inline-block;">
						<div style="text-transform:uppercase;padding-bottom:6px;font-family: 'dinRegular';" class="clearfix">
							<%= current_user.name %>
						</div>
						<div id="user-statistics">
							<div style="display:inline-block;padding-right:12px;vertical-align:top;">
								<div>
									<a href="<%= my_votes_path %>" data-toggle="tooltip" data-placement="bottom" title="Votes">
										<div style="vertical-align:top;">
											<img src="<%= image_path('icon-vote.png') %>" style="width:21px;height:24px;" class="image" title="votes" />
										</div>
									</a>
								</div>
								<div id="votes-count" class="text-center top_banner_num_text">
									<%= current_user.votes_count %> 
								</div>
							</div>
							<div style="display:inline-block;padding-right:12px;">
								<div>
								<a href="<%= following_path %>" data-toggle="tooltip" data-placement="bottom" title="Following">
									<% if _svg == true %>
									<div style="width:21px;" title="following">
										<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 21 23.9" enable-background="new 0 0 21 23.9" xml:space="preserve">
										<path fill="#898989" d="M9.6,0.5L9.6,0.5c3,0,5.3,0.8,7,2.6c1,1,1.6,2.3,1.8,4c0.1,0.9,0.1,1.9-0.1,2.9c-0.1,0.5,0.1,1,0.2,1.3
											c0.3,0.6,0.6,1.1,1,1.5c0.1,0.1,0.2,0.3,0.3,0.4c0.2,0.3,0.4,0.6,0.6,0.9c0.1,0.1,0,0.1,0,0.2c-0.3,0.2-0.6,0.4-0.9,0.4
											c-0.1,0-0.5,0.1-0.7,0.4c-0.2,0.3,0,0.7,0.1,0.8c0.1,0.2,0.2,0.4,0.2,0.6c0,0.1,0,0.2,0,0.2c0,0-0.1,0-0.1,0c0,0-0.1,0-0.2,0
											c-0.1,0-0.1,0-0.2,0c-0.1,0-0.2,0-0.3,0h-1.2l0.8,0.8c0.1,0.1,0.2,0.2,0.2,0.2c0.1,0.1,0.3,0.3,0.3,0.4c0,0,0,0.1,0,0.1
											c0,0,0,0-0.1,0.1c-0.2,0.2-0.5,0.4-0.7,0.5c-0.5,0.2-0.7,0.5-0.7,1c0,0.3,0,0.5-0.2,0.9c-0.1,0.3-0.4,0.7-0.9,0.7l-0.1,0
											c-0.9-0.1-1.8-0.1-2.5-0.7l-0.6-0.4l-0.2,0.7l-0.2,0.7c-0.1,0.5-0.3,1.1-0.4,1.6c-1.3,0-2.6,0-3.9,0c-1.2,0-2.4,0-3.6,0
											c0-0.8,0.1-1.6,0.1-2.4c0-0.9,0.1-1.7,0.1-2.6c0-0.4-0.2-0.7-0.4-0.9c-1.8-2.2-3-4.2-3.6-6.3c-0.3-0.9-0.6-1.9-0.5-2.8l0-0.3
											c0.2-1.4,0.3-2.6,0.8-3.8C2,2.9,3.2,1.9,5,1.3c1.3-0.5,2.7-0.7,4.1-0.8C9.3,0.5,9.4,0.5,9.6,0.5 M9.6,0C9.4,0,9.2,0,9,0
											c-1.4,0-2.9,0.3-4.2,0.8C3.1,1.4,1.7,2.4,1,4.1C0.3,5.4,0.2,6.9,0,8.4c-0.1,1,0.2,2,0.5,3c0.8,2.4,2.1,4.5,3.7,6.4
											c0.1,0.2,0.3,0.3,0.2,0.5c-0.1,1.7-0.2,3.5-0.3,5.2c0,0.3,0,0.4,0.3,0.4c0,0,0,0,0,0c1.3,0,2.5,0,3.8,0c1.3,0,2.6,0,3.9,0
											c0,0,0,0,0,0c0.3,0,0.4-0.1,0.4-0.4c0.2-0.8,0.4-1.5,0.5-2.3C14.1,21.9,15,22,16,22c0,0,0.1,0,0.1,0c0.7,0,1.2-0.4,1.4-1
											c0.1-0.3,0.2-0.7,0.2-1.1c0-0.3,0.1-0.4,0.4-0.5c0.3-0.1,0.6-0.3,0.8-0.5c0.3-0.2,0.3-0.5,0.1-0.8c-0.2-0.2-0.4-0.4-0.6-0.7
											c0.2,0,0.3,0,0.5,0c0.1,0,0.2,0,0.2,0c0.5-0.1,0.6-0.3,0.5-0.8c-0.1-0.3-0.1-0.6-0.3-0.8c-0.2-0.3-0.2-0.4,0.2-0.5
											c0.4-0.1,0.8-0.2,1.2-0.5c0.3-0.2,0.3-0.5,0.2-0.8c-0.2-0.4-0.4-0.7-0.6-1c-0.4-0.6-0.9-1.2-1.3-1.9c-0.2-0.3-0.3-0.6-0.2-1
											C19,9.1,19.1,8,19,7c-0.2-1.7-0.8-3.1-2-4.3C15,0.6,12.4,0,9.6,0L9.6,0z"/>
										</svg>
									</div>
									<% else %>
									<img src="<%= image_path('icon-engage-single.png') %>" style="width:21px" class="image" title="Following" />
									<% end %>
								</a><!-- add this functionality still -->
								</div>
								<div id="followers-count" class="text-center top_banner_num_text">
									<%= current_user.followed_users.count %>
								</div>
							</div>

							<div style="display:inline-block;padding-right:12px;">
								<div>
								<a href="<%= followers_path %>" data-toggle="tooltip" data-placement="bottom" title="Followers">
									<% if _svg == true %>
									<div style="width:21px;" class="flipped-horizontal" title="followers">
										<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 21 23.9" enable-background="new 0 0 21 23.9" xml:space="preserve">
										<path fill="#898989" d="M9.6,0.5L9.6,0.5c3,0,5.3,0.8,7,2.6c1,1,1.6,2.3,1.8,4c0.1,0.9,0.1,1.9-0.1,2.9c-0.1,0.5,0.1,1,0.2,1.3
											c0.3,0.6,0.6,1.1,1,1.5c0.1,0.1,0.2,0.3,0.3,0.4c0.2,0.3,0.4,0.6,0.6,0.9c0.1,0.1,0,0.1,0,0.2c-0.3,0.2-0.6,0.4-0.9,0.4
											c-0.1,0-0.5,0.1-0.7,0.4c-0.2,0.3,0,0.7,0.1,0.8c0.1,0.2,0.2,0.4,0.2,0.6c0,0.1,0,0.2,0,0.2c0,0-0.1,0-0.1,0c0,0-0.1,0-0.2,0
											c-0.1,0-0.1,0-0.2,0c-0.1,0-0.2,0-0.3,0h-1.2l0.8,0.8c0.1,0.1,0.2,0.2,0.2,0.2c0.1,0.1,0.3,0.3,0.3,0.4c0,0,0,0.1,0,0.1
											c0,0,0,0-0.1,0.1c-0.2,0.2-0.5,0.4-0.7,0.5c-0.5,0.2-0.7,0.5-0.7,1c0,0.3,0,0.5-0.2,0.9c-0.1,0.3-0.4,0.7-0.9,0.7l-0.1,0
											c-0.9-0.1-1.8-0.1-2.5-0.7l-0.6-0.4l-0.2,0.7l-0.2,0.7c-0.1,0.5-0.3,1.1-0.4,1.6c-1.3,0-2.6,0-3.9,0c-1.2,0-2.4,0-3.6,0
											c0-0.8,0.1-1.6,0.1-2.4c0-0.9,0.1-1.7,0.1-2.6c0-0.4-0.2-0.7-0.4-0.9c-1.8-2.2-3-4.2-3.6-6.3c-0.3-0.9-0.6-1.9-0.5-2.8l0-0.3
											c0.2-1.4,0.3-2.6,0.8-3.8C2,2.9,3.2,1.9,5,1.3c1.3-0.5,2.7-0.7,4.1-0.8C9.3,0.5,9.4,0.5,9.6,0.5 M9.6,0C9.4,0,9.2,0,9,0
											c-1.4,0-2.9,0.3-4.2,0.8C3.1,1.4,1.7,2.4,1,4.1C0.3,5.4,0.2,6.9,0,8.4c-0.1,1,0.2,2,0.5,3c0.8,2.4,2.1,4.5,3.7,6.4
											c0.1,0.2,0.3,0.3,0.2,0.5c-0.1,1.7-0.2,3.5-0.3,5.2c0,0.3,0,0.4,0.3,0.4c0,0,0,0,0,0c1.3,0,2.5,0,3.8,0c1.3,0,2.6,0,3.9,0
											c0,0,0,0,0,0c0.3,0,0.4-0.1,0.4-0.4c0.2-0.8,0.4-1.5,0.5-2.3C14.1,21.9,15,22,16,22c0,0,0.1,0,0.1,0c0.7,0,1.2-0.4,1.4-1
											c0.1-0.3,0.2-0.7,0.2-1.1c0-0.3,0.1-0.4,0.4-0.5c0.3-0.1,0.6-0.3,0.8-0.5c0.3-0.2,0.3-0.5,0.1-0.8c-0.2-0.2-0.4-0.4-0.6-0.7
											c0.2,0,0.3,0,0.5,0c0.1,0,0.2,0,0.2,0c0.5-0.1,0.6-0.3,0.5-0.8c-0.1-0.3-0.1-0.6-0.3-0.8c-0.2-0.3-0.2-0.4,0.2-0.5
											c0.4-0.1,0.8-0.2,1.2-0.5c0.3-0.2,0.3-0.5,0.2-0.8c-0.2-0.4-0.4-0.7-0.6-1c-0.4-0.6-0.9-1.2-1.3-1.9c-0.2-0.3-0.3-0.6-0.2-1
											C19,9.1,19.1,8,19,7c-0.2-1.7-0.8-3.1-2-4.3C15,0.6,12.4,0,9.6,0L9.6,0z"/>
										</svg>
									</div>
									<% else %>
									<img src="<%= image_path('icon-engage-single.png') %>" style="width:21px" class="image flipped-horizontal" title="followers" />
									<% end %>
								</a><!-- add this functionality still -->
								</div>
								<div id="followers-count" class="text-center top_banner_num_text">
									<%= current_user.followers.count %>
								</div>
							</div>




							<div style="display:inline-block;vertical-align:top;">
								<a href="<%= edit_user_path(current_user) %>" data-toggle="tooltip" data-placement="bottom" title="Settings"><i class="fa fa-cog fa-2x" style="color:#8a8a8a;" title="settings"></i></a>
							</div>
						</div><!--#user-statistics-->
					</div><!-- #user-info -->
				</div>
			</div>
		</div>
		<div class="col-sm-4" style="text-align: center;border-bottom: 1px solid #C9C9C9;">
			<img src="<%= image_path('terms-image-850.png') %>" class="width_100" style="height: 73px;width: 190px;">
		</div>
		<div class="col-sm-4 text-right extra_mp_padding">
			<div class="row">
				<div class="col-sm-12" style="padding-right: 0;">
					<% 
						if current_user.constituency && current_user.constituency.mp
						@mp = current_user.constituency.mp
					%>
					<div id="mp-info" style="display:inline-block;">
						<div style="text-transform:uppercase; font-family: 'dinRegular';" class="clearfix">
							<%= @mp.name %>
						</div>
						<div id="mp-statistics">
							<div class="clearfix" style="padding-bottom:6px;color: #999999;font-size:12px; font-family: 'dinRegular';letter-spacing: 1px;">
								MP for <%= @mp.constituency.name %><br>
							</div>
							  <% if @mp.email != "" %>
					              <div style="display:inline-block;padding-right:12px;">
					                <a href="#" class="email-link" id="mp_email_modal"><img src="<%= image_path('email_icon.png') %>"></a>
					              </div>
					          <% end %>
					          <% if @mp.fb_link %>
					            <div style="display:inline-block;padding-right:12px;">
					              <a href="<%= @mp.fb_link %>" class="facebook-link" target="_blank"><img src="<%= image_path('fb_icon.png') %>"></a>
					            </div>
					          <% else %>
					          	<div style="display:inline-block;padding-right:12px;">
					              <a href="#" class="facebook-link" id="no_fb_modal"><img src="<%= image_path('no_fb_icon.png') %>"></a>
					            </div>
					          <% end %>
					          <% if @mp.tw_link %>
					            <div style="display:inline-block;">
					              <a href="<%= @mp.tw_link %>" class="twitter-link" target="_blank"><img src="<%= image_path('tw_icon.png') %>"></a>
					            </div>
					          <% else %>
					          	<div style="display:inline-block;">
					              <a href="#" class="twitter-link" id="no_tw_modal"><img src="<%= image_path('no_tw_icon.png') %>"></a>
					            </div>
					          <% end %>
						</div><!-- #mp-statistics -->
					</div><!-- #mp-info -->
					<div id="mp-image" style="text-transform:uppercase;display:inline-block;vertical-align:top;padding-left:12px;">
						<img src="<%= @mp.picture_url %>" style="height:65px;width:65px;background-color:#10b8b8;border:none;border-radius:50%;" />
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>

<% else %>
	<div class="row" style="">
		<div class="col-sm-4 col-xs-12 extra_social_padding" style="">
			<div class="" style="padding-top: 6px;">
				<p class="headers">SOCIAL SIGN UP</p>
				<a href="<%= root_url %>users/auth/facebook?image_size=large"><!--SIGN IN WITH FACEBOOK--><i class="fa fa-facebook fa-2x" style="color:#3b589e;padding-right: 10px;"></i></a>
				<a href="<%= root_url %>users/auth/twitter?image_size=original"><!--SIGN IN WITH TWITTER--><i class="fa fa-twitter fa-2x" style="color:#20b8ff;"></i></a>
			</div>
		</div>
		<div class="col-sm-4 col-sm-4 col-xs-12" style="text-align: center;border-bottom: 1px solid #C9C9C9;">
			<img src="<%= image_path('terms-image-850.png') %>" class="width_100" style="height: 73px;width: 190px;">
		</div>
		<div class="col-sm-4 col-sm-4 col-xs-12 extra_mp_padding">
			<div class="" style="text-align: center;padding-top: 6px;">
				<p class="headers">EMAIL SIGN UP</p>
				<a class="" href="#" data-toggle="modal" data-target="#emailsignUpModal"><img src="<%= image_path('email_icon.png') %>" style="height:22px;"></a>
			</div>
		</div>
	</div>

<% end %>

<script type="text/javascript">
var ready;
ready = function() {

	$('body').off('click','#no_fb_modal');
	$('body').on('click', '#no_fb_modal', function(e){
		e.preventDefault();

		$('#noFBModal').modal('show');

	});

	$('body').off('click','#no_tw_modal');
	$('body').on('click', '#no_tw_modal', function(e){
		e.preventDefault();

		$('#noTWModal').modal('show');

	});

	$('body').off('click','#mp_email_modal');
	$('body').on('click', '#mp_email_modal', function(e){
		e.preventDefault();

		$('#mpEmailModal').modal('show');

	});

};

$(document).ready(ready);
$(document).on('page:load', ready);
</script>

app/views/bills/index.js.erb
$("body").append("<div id='hold_common_bills'><%= escape_javascript(render(@commons)) %></div>");